services:
  nginx:
    container_name: golem-nginx
    image: nginx:stable-alpine
    logging:
      driver: journald
      options:
        tag: "golem-nginx"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /home/${GOLEM_DEPLOY_USERNAME:-ubuntu}/geneweb/deployment/nginx/nginx.conf.template:/etc/nginx/nginx.conf.template
      - /home/${GOLEM_DEPLOY_USERNAME:-ubuntu}/geneweb/deployment/nginx/snippets:/etc/nginx/snippets
    entrypoint: >
      /bin/sh -c "envsubst '$$SERVER_NAME' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
    environment:
      SERVER_NAME: ${GOLEM_SERVER_NAME}
    depends_on:
      api:
        condition: service_healthy
    networks:
      - golem-network
    restart: unless-stopped

  db:
    container_name: golem-db
    image: postgres:17-alpine
    volumes:
      - golem-db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${GOLEM_DATABASE_PASSWORD}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - golem-network
    restart: unless-stopped

  api:
    container_name: golem-api
    build:
      context: ../backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      GOLEM_DATABASE_URL: "postgresql+asyncpg://postgres:${GOLEM_DATABASE_PASSWORD}@db:5432/postgres"
      GOLEM_DATA_DIR: "/data"
      GOLEM_ACCESS_TOKEN_EXPIRE_MINUTES: 30
      GOLEM_SECRET_KEY: ${GOLEM_SECRET_KEY}
    volumes:
      - /home/${GOLEM_DEPLOY_USERNAME:-ubuntu}/geneweb-data:/data
    depends_on:
      db:
        condition: service_healthy
    networks:
      - golem-network
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "python",
          "-c",
          "import urllib.request;",
          "urllib.request.urlopen('http://localhost:8000/api/v1/ready/')",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  ui:
    container_name: golem-ui
    build:
      context: ../ui
      dockerfile: Dockerfile
      args:
        GOLEM_API_URL: https://${GOLEM_SERVER_NAME}/api/v1
    ports:
      - "3000:3000"
    networks:
      - golem-network
    restart: unless-stopped

networks:
  golem-network:

volumes:
  golem-db-data:
