@startuml database_schema

skinparam Linetype ortho
skinparam Nodesep 80
skinparam Ranksep 50
skinparam backgroundColor transparent

hide circle

entity users {
    *id: uuid
    ---
    *username: varchar
    *password_hash: varchar
}

entity groups {
    *id: uuid
    ---
    *name: varchar
}

entity users_groups {
    *user_id: <<FK users>>
    *group_id: <<FK groups>>
}

entity organisms {
    *id: uuid
    ---
    *name: varchar
    *filename: varchar
    *public: bool
}

entity organisms_groups {
    *organism_id: uuid
    *group_id: uuid
}

entity alembic_version {
    *version_num: varchar
}

users  |o.. users_groups
groups |o.. users_groups

groups |o.. organisms_groups
organisms |o.. organisms_groups

@enduml