"""rename is_public to public

Revision ID: 58c0f00904d9
Revises: 6b5470ab3b5a
Create Date: 2025-09-16 23:04:53.041857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '58c0f00904d9'
down_revision: Union[str, Sequence[str], None] = '6b5470ab3b5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('motifs', sa.Column('public', sa.Boolean(), nullable=False))
    op.drop_column('motifs', 'is_public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('motifs', sa.Column('is_public', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('motifs', 'public')
    # ### end Alembic commands ###
