"""add motif tables, take_first_transcript_only column

Revision ID: 6b5470ab3b5a
Revises: 9f740ece1877
Create Date: 2025-09-16 22:07:28.851631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6b5470ab3b5a'
down_revision: Union[str, Sequence[str], None] = '9f740ece1877'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('motifs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('motif_definitions',
    sa.Column('definition', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('motif_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['motif_id'], ['motifs.id'], ),
    sa.PrimaryKeyConstraint('definition', 'motif_id')
    )
    op.add_column('organisms', sa.Column('take_first_transcript_only', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organisms', 'take_first_transcript_only')
    op.drop_table('motif_definitions')
    op.drop_table('motifs')
    # ### end Alembic commands ###
