"""make user stage preference per organism

Revision ID: 71834dfc5a17
Revises: 58c0f00904d9
Create Date: 2025-10-06 21:12:18.800958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '71834dfc5a17'
down_revision: Union[str, Sequence[str], None] = '58c0f00904d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_stages_preferences', sa.Column('organism_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'user_stages_preferences', 'organisms', ['organism_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_stages_preferences', type_='foreignkey')
    op.drop_column('user_stages_preferences', 'organism_id')
    # ### end Alembic commands ###
