"""add metadata file column to organism

Revision ID: c607e57ba557
Revises: b5e6c0f11f30
Create Date: 2025-08-17 11:46:58.721095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c607e57ba557'
down_revision: Union[str, Sequence[str], None] = 'b5e6c0f11f30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organisms', sa.Column('sequences_filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('organisms', sa.Column('metadata_filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_column('organisms', 'filename')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organisms', sa.Column('filename', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('organisms', 'metadata_filename')
    op.drop_column('organisms', 'sequences_filename')
    # ### end Alembic commands ###
