name: geneweb
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.2.1+6

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  provider: ^6.0.3
  community_charts_flutter: ^1.0.4
  crypto: ^3.0.1
  equatable: ^2.0.3
  file_picker: ^8.1.2
  excel: ^4.0.3
  universal_file: ^1.0.0
  faabul_color_picker: ^1.0.2
  archive: ^3.3.1
  truncate: ^3.0.1
  collection: ^1.16.0
  sanitize_filename: ^1.0.4
  flutter_svg: ^2.0.10+1
  file_saver: ^0.2.14
  share_plus: ^10.0.2
  flutter_native_splash: ^2.1.0
  csv: ^6.0.0
  url_launcher: ^6.2.1
  dio: ^5.9.0
  dio_web_adapter: ^2.1.1
  web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/

  fonts:
    - family: Barlow
      fonts:
        - asset: assets/fonts/Barlow-Regular.ttf
        - asset: assets/fonts/Barlow-Italic.ttf
          style: italic
        - asset: assets/fonts/Barlow-Bold.ttf

flutter_native_splash:
  color: "#A0CB85"
  image: assets/loading.png
