name: GOLEM Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        options: ["Production", "Development"]
        required: true
        description: "Select the environment to deploy to"

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ vars.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT || 22}}
          command_timeout: 60m
          script: |
            set -e

            BRANCH_NAME="${{ github.ref_name }}"

            echo "Deploying from branch [$BRANCH_NAME]"

            echo "Setting up environment variables ..."
            export GOLEM_SECRET_KEY=${{ secrets.GOLEM_SECRET_KEY }}
            export GOLEM_DATABASE_PASSWORD=${{ secrets.GOLEM_DATABASE_PASSWORD }}
            export GOLEM_SERVER_NAME=${{ vars.GOLEM_SERVER_NAME }}
            export GOLEM_DEPLOY_USERNAME=${{ secrets.SSH_USERNAME }}

            echo "Navigating to the deployment directory ..."
            cd /home/${{ secrets.SSH_USERNAME }}/geneweb/deployment

            echo "Pulling latest changes ..."
            sudo git fetch --all
            sudo git checkout $BRANCH_NAME
            sudo git reset --hard origin/$BRANCH_NAME

            echo "Building images ..."
            sudo -E docker compose build

            echo "Starting new containers ..."
            sudo -E docker compose up -d --remove-orphans

            echo "Listing containers ..."
            sudo docker compose ps

            echo "Cleaning up old images ..."
            sudo docker image prune -f
